platform :ios ,'7.0'
pod 'MDRadialProgress'
pod 'PNChart'
#pod 'BlocksKit'
pod 'BaseModel'
pod 'AutoCoding'
#pod 'SIAlertView'
pod 'UIColor+MLPFlatColors'
pod 'Colours'
pod 'iOS7Colors'
pod 'NSDate+Helper'